export const leafColumns = [
  { key: "siteName", label: "Site Name" },
  { key: "startTime", label: "Start Time" },
  { key: "endTime", label: "End Time" },
  { key: "periodDays", label: "Period (Days)" },
  { key: "dgRunStart", label: "Start" },
  { key: "dgRunEnd", label: "End" },
  { key: "dgRhPerDay", label: "DGRH Per Day" },
  { key: "dgTotalRunHr", label: "DG Total Run Hr" },
  { key: "gridRunStart", label: "Start" },
  { key: "gridRunEnd", label: "End" },
  { key: "gridRhPerDay", label: "Grid RH Per Day" },
  { key: "gridTotalRunHr", label: "Grid Total Run Hr" },
  { key: "batteryRunStart", label: "Start" },
  { key: "batteryRunEnd", label: "End" },
  { key: "batteryRhPerDay", label: "Battery RH Per Day" },
  { key: "batteryTotalRunHr", label: "Battery Total Run Hr" },
  { key: "solarRunStart", label: "Start" },
  { key: "solarRunEnd", label: "End" },
  { key: "solarRhPerDay", label: "Solar RH Per Day" },
  { key: "solarTotalRunHr", label: "Solar Total Run Hr" },
  { key: "totalRunHrPerDays", label: "Total Run Hr per days" },
  { key: "dgKwhStart", label: "Start" },
  { key: "dgKwhEnd", label: "End" },
  { key: "dgKwhPerDay", label: "DG KWH Per Day" },
  { key: "gridKwhStart", label: "Start" },
  { key: "gridKwhEnd", label: "End" },
  { key: "gridKwhPerDay", label: "Grid KWH Per Day" },
  { key: "batteryKwhStart", label: "Start" },
  { key: "batteryKwhEnd", label: "End" },
  { key: "batteryKwhPerDay", label: "Battery KWH Per Day" },
  { key: "solarGenKwhStart", label: "Start" },
  { key: "solarGenKwhEnd", label: "End" },
  { key: "solarGenKwhPerDay", label: "Solar KWH Per Day" },
  { key: "solarLoadKwhStart", label: "Start" },
  { key: "solarLoadKwhEnd", label: "End" },
  { key: "solarLoadKwhPerDay", label: "Solar Load Per Day" },
] as const;

export type EnergyLeafKey = (typeof leafColumns)[number]["key"];
