/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMinorAlarmIndexRouteImport } from './routes/_authenticated/minor-alarm/index'
import { Route as AuthenticatedMappingIndexRouteImport } from './routes/_authenticated/mapping/index'
import { Route as AuthenticatedMajorAlarmIndexRouteImport } from './routes/_authenticated/major-alarm/index'
import { Route as AuthenticatedLogIndexRouteImport } from './routes/_authenticated/log/index'
import { Route as AuthenticatedLoadConsumptionIndexRouteImport } from './routes/_authenticated/load-consumption/index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedEnergyConsumptionIndexRouteImport } from './routes/_authenticated/energy-consumption/index'
import { Route as AuthenticatedCritialAlarmIndexRouteImport } from './routes/_authenticated/critial-alarm/index'
import { Route as AuthenticatedActiveAlarmIndexRouteImport } from './routes/_authenticated/active-alarm/index'
import { Route as AuthenticatedChartIdRouteImport } from './routes/_authenticated/chart/$id'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMinorAlarmIndexRoute =
  AuthenticatedMinorAlarmIndexRouteImport.update({
    id: '/minor-alarm/',
    path: '/minor-alarm/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMappingIndexRoute =
  AuthenticatedMappingIndexRouteImport.update({
    id: '/mapping/',
    path: '/mapping/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMajorAlarmIndexRoute =
  AuthenticatedMajorAlarmIndexRouteImport.update({
    id: '/major-alarm/',
    path: '/major-alarm/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLogIndexRoute = AuthenticatedLogIndexRouteImport.update({
  id: '/log/',
  path: '/log/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLoadConsumptionIndexRoute =
  AuthenticatedLoadConsumptionIndexRouteImport.update({
    id: '/load-consumption/',
    path: '/load-consumption/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEnergyConsumptionIndexRoute =
  AuthenticatedEnergyConsumptionIndexRouteImport.update({
    id: '/energy-consumption/',
    path: '/energy-consumption/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCritialAlarmIndexRoute =
  AuthenticatedCritialAlarmIndexRouteImport.update({
    id: '/critial-alarm/',
    path: '/critial-alarm/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedActiveAlarmIndexRoute =
  AuthenticatedActiveAlarmIndexRouteImport.update({
    id: '/active-alarm/',
    path: '/active-alarm/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChartIdRoute = AuthenticatedChartIdRouteImport.update({
  id: '/chart/$id',
  path: '/chart/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/chart/$id': typeof AuthenticatedChartIdRoute
  '/active-alarm/': typeof AuthenticatedActiveAlarmIndexRoute
  '/critial-alarm/': typeof AuthenticatedCritialAlarmIndexRoute
  '/energy-consumption/': typeof AuthenticatedEnergyConsumptionIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/load-consumption/': typeof AuthenticatedLoadConsumptionIndexRoute
  '/log/': typeof AuthenticatedLogIndexRoute
  '/major-alarm/': typeof AuthenticatedMajorAlarmIndexRoute
  '/mapping/': typeof AuthenticatedMappingIndexRoute
  '/minor-alarm/': typeof AuthenticatedMinorAlarmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/chart/$id': typeof AuthenticatedChartIdRoute
  '/active-alarm': typeof AuthenticatedActiveAlarmIndexRoute
  '/critial-alarm': typeof AuthenticatedCritialAlarmIndexRoute
  '/energy-consumption': typeof AuthenticatedEnergyConsumptionIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/load-consumption': typeof AuthenticatedLoadConsumptionIndexRoute
  '/log': typeof AuthenticatedLogIndexRoute
  '/major-alarm': typeof AuthenticatedMajorAlarmIndexRoute
  '/mapping': typeof AuthenticatedMappingIndexRoute
  '/minor-alarm': typeof AuthenticatedMinorAlarmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/chart/$id': typeof AuthenticatedChartIdRoute
  '/_authenticated/active-alarm/': typeof AuthenticatedActiveAlarmIndexRoute
  '/_authenticated/critial-alarm/': typeof AuthenticatedCritialAlarmIndexRoute
  '/_authenticated/energy-consumption/': typeof AuthenticatedEnergyConsumptionIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/load-consumption/': typeof AuthenticatedLoadConsumptionIndexRoute
  '/_authenticated/log/': typeof AuthenticatedLogIndexRoute
  '/_authenticated/major-alarm/': typeof AuthenticatedMajorAlarmIndexRoute
  '/_authenticated/mapping/': typeof AuthenticatedMappingIndexRoute
  '/_authenticated/minor-alarm/': typeof AuthenticatedMinorAlarmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chart/$id'
    | '/active-alarm/'
    | '/critial-alarm/'
    | '/energy-consumption/'
    | '/inventory/'
    | '/load-consumption/'
    | '/log/'
    | '/major-alarm/'
    | '/mapping/'
    | '/minor-alarm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chart/$id'
    | '/active-alarm'
    | '/critial-alarm'
    | '/energy-consumption'
    | '/inventory'
    | '/load-consumption'
    | '/log'
    | '/major-alarm'
    | '/mapping'
    | '/minor-alarm'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/'
    | '/_authenticated/chart/$id'
    | '/_authenticated/active-alarm/'
    | '/_authenticated/critial-alarm/'
    | '/_authenticated/energy-consumption/'
    | '/_authenticated/inventory/'
    | '/_authenticated/load-consumption/'
    | '/_authenticated/log/'
    | '/_authenticated/major-alarm/'
    | '/_authenticated/mapping/'
    | '/_authenticated/minor-alarm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minor-alarm/': {
      id: '/_authenticated/minor-alarm/'
      path: '/minor-alarm'
      fullPath: '/minor-alarm/'
      preLoaderRoute: typeof AuthenticatedMinorAlarmIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapping/': {
      id: '/_authenticated/mapping/'
      path: '/mapping'
      fullPath: '/mapping/'
      preLoaderRoute: typeof AuthenticatedMappingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/major-alarm/': {
      id: '/_authenticated/major-alarm/'
      path: '/major-alarm'
      fullPath: '/major-alarm/'
      preLoaderRoute: typeof AuthenticatedMajorAlarmIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/log/': {
      id: '/_authenticated/log/'
      path: '/log'
      fullPath: '/log/'
      preLoaderRoute: typeof AuthenticatedLogIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/load-consumption/': {
      id: '/_authenticated/load-consumption/'
      path: '/load-consumption'
      fullPath: '/load-consumption/'
      preLoaderRoute: typeof AuthenticatedLoadConsumptionIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/energy-consumption/': {
      id: '/_authenticated/energy-consumption/'
      path: '/energy-consumption'
      fullPath: '/energy-consumption/'
      preLoaderRoute: typeof AuthenticatedEnergyConsumptionIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/critial-alarm/': {
      id: '/_authenticated/critial-alarm/'
      path: '/critial-alarm'
      fullPath: '/critial-alarm/'
      preLoaderRoute: typeof AuthenticatedCritialAlarmIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/active-alarm/': {
      id: '/_authenticated/active-alarm/'
      path: '/active-alarm'
      fullPath: '/active-alarm/'
      preLoaderRoute: typeof AuthenticatedActiveAlarmIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chart/$id': {
      id: '/_authenticated/chart/$id'
      path: '/chart/$id'
      fullPath: '/chart/$id'
      preLoaderRoute: typeof AuthenticatedChartIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedChartIdRoute: typeof AuthenticatedChartIdRoute
  AuthenticatedActiveAlarmIndexRoute: typeof AuthenticatedActiveAlarmIndexRoute
  AuthenticatedCritialAlarmIndexRoute: typeof AuthenticatedCritialAlarmIndexRoute
  AuthenticatedEnergyConsumptionIndexRoute: typeof AuthenticatedEnergyConsumptionIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedLoadConsumptionIndexRoute: typeof AuthenticatedLoadConsumptionIndexRoute
  AuthenticatedLogIndexRoute: typeof AuthenticatedLogIndexRoute
  AuthenticatedMajorAlarmIndexRoute: typeof AuthenticatedMajorAlarmIndexRoute
  AuthenticatedMappingIndexRoute: typeof AuthenticatedMappingIndexRoute
  AuthenticatedMinorAlarmIndexRoute: typeof AuthenticatedMinorAlarmIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedChartIdRoute: AuthenticatedChartIdRoute,
  AuthenticatedActiveAlarmIndexRoute: AuthenticatedActiveAlarmIndexRoute,
  AuthenticatedCritialAlarmIndexRoute: AuthenticatedCritialAlarmIndexRoute,
  AuthenticatedEnergyConsumptionIndexRoute:
    AuthenticatedEnergyConsumptionIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedLoadConsumptionIndexRoute:
    AuthenticatedLoadConsumptionIndexRoute,
  AuthenticatedLogIndexRoute: AuthenticatedLogIndexRoute,
  AuthenticatedMajorAlarmIndexRoute: AuthenticatedMajorAlarmIndexRoute,
  AuthenticatedMappingIndexRoute: AuthenticatedMappingIndexRoute,
  AuthenticatedMinorAlarmIndexRoute: AuthenticatedMinorAlarmIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
